http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:

  api:
    host: localhost
    paths: '/ip'
  user-manager:
    host: localhost
    paths: 
        - '/users/*'
 
  bet-manager:
    host: localhost
    paths: 
        - '/bets/*'
        
serviceEndpoints:

  httpbin:
    url: 'https://httpbin.org'
  user-manager-service:
    url : 'http://localhost:3001/'
  bet-manager-service:
    url : 'http://localhost:3002/'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:

  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
        - action:
            serviceEndpoint: httpbin 
            changeOrigin: true

  user-manager-pipe:
    apiEndpoints: user-manager
    policies: 
      - proxy:
        - action:
            serviceEndpoint: user-manager-service
    
  bet-manager-pipe:
    apiEndpoints: bet-manager
    policies: 
      - proxy:
        - action:
            serviceEndpoint: bet-manager-service
    
